version: 2
jobs:
  test:
    steps:
      - checkout
      - run: su postgres -c './pitrery help'
      - run: su postgres -c './pitrery check'
      - run: su postgres -c './pitrery backup'
      - run: su postgres -c './pitrery list'  
