version: 2

jobs:
  build:
    machine: true
    steps:
      - checkout 
      - run: sudo apt-get update && sudo apt-get install postgresql
      - run: sudo -u postgres ./pitrery help
      - run: sudo -u postgres ./pitrery check
      - run: sudo -u postgres ./pitrery backup
      - run: sudo -u postgres ./pitrery list 
