version: 2

jobs:
  build:
    machine: true
    steps:
      - checkout 
      - run: apt-get install postgresql  
      - run: su postgres -c './pitrery help'
      - run: su postgres -c './pitrery check'
      - run: su postgres -c './pitrery backup'
      - run: su postgres -c './pitrery list'  
